# 调度器配置文件
# 包含定时任务的时间、频率、股票列表等配置

# 数据收集配置
data_collection:
  # 实时数据收集配置
  realtime_tick_interval: 30      # 实时Tick数据收集间隔(秒)
  realtime_bar_interval: 60       # 实时Bar数据收集间隔(秒)
  
  # 定时全量同步配置
  daily_sync_times:
    - "09:00"    # 开盘前全量同步
    - "12:00"    # 午盘前全量同步
    - "15:05"    # 收盘后全量同步
  
  # 市场状态检查配置
  market_status_check_interval: 5  # 市场状态检查间隔(分钟)
  
  # 数据频率配置
  supported_frequencies:
    - "60s"      # 1分钟
    - "300s"     # 5分钟
    - "900s"     # 15分钟
    - "1d"       # 日线
  
  # 默认股票列表
  default_sh_symbols:  # 上海市场
    - "600000"   # 浦发银行
    - "600036"   # 招商银行
    - "600519"   # 贵州茅台
    - "600887"   # 伊利股份
    - "601318"   # 中国平安
  
  default_sz_symbols:  # 深圳市场
    - "000001"   # 平安银行
    - "000002"   # 万科A
    - "000858"   # 五粮液
    - "002415"   # 海康威视
    - "300059"   # 东方财富
  
  # 交易时间配置
  trading_hours:
    morning:
      - "09:30"  # 上午开盘
      - "11:30"  # 上午收盘
    afternoon:
      - "13:00"  # 下午开盘
      - "15:00"  # 下午收盘
  
  # 周末是否交易
  weekend_trading: false

# 任务调度配置
tasks:
  - name: "实时数据同步"
    enabled: true
    interval_type: "seconds"
    interval_value: 30
    description: "交易时间每30秒同步实时数据"
  
  - name: "开盘前全量同步"
    enabled: true
    interval_type: "daily"
    interval_value: 1
    at_time: "09:00"
    description: "每日开盘前全量同步数据"
  
  - name: "午盘前全量同步"
    enabled: true
    interval_type: "daily"
    interval_value: 1
    at_time: "12:00"
    description: "每日午盘前全量同步数据"
  
  - name: "收盘后全量同步"
    enabled: true
    interval_type: "daily"
    interval_value: 1
    at_time: "15:05"
    description: "每日收盘后全量同步数据"
  
  - name: "市场状态检查"
    enabled: true
    interval_type: "minutes"
    interval_value: 5
    description: "每5分钟检查市场状态"

# 调度器运行配置
scheduler:
  sleep_interval: 1        # 调度器主循环休眠间隔(秒)
  exception_wait: 5        # 调度器异常时等待时间(秒)
  max_retry_count: 3       # 最大重试次数
  retry_wait_time: 1       # 重试等待时间(秒)
  batch_size: 1000         # 批处理大小
  batch_timeout: 30        # 批处理超时时间(秒)

# 高级配置
advanced:
  # 是否启用动态调整
  enable_dynamic_adjustment: true
  
  # 是否启用性能监控
  enable_performance_monitoring: true
  
  # 是否启用错误告警
  enable_error_alerting: true
  
  # 日志级别
  log_level: "INFO"
  
  # 是否保存历史数据
  save_historical_data: true
  
  # 数据保留天数
  data_retention_days: 365
